version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    links:
    - mongo
  mongo:
    image: mongo:latest
    hostname: mongodb
    environment:
      MONGO_INITDB_DATABASE: my_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
